TranThiThuyLoan/TestUngDung/Areas/Admin/Controllers/HomeController.cs
using ModelEF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestUngDung.Areas.Admin.Model;

namespace TestUngDung.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        // GET: Admin/Home
        public ActionResult Index()
        {
            var session = (LoginModel)Session[Constants.USER_SESSION];
            if (session == null) return RedirectToAction("Index", "Login");
            return View();
        }
        public ActionResult Logout()
        {
            Session[Constants.USER_SESSION] = null;
            return RedirectToAction("Index", "Login");
        }
    }
}

TranThiThuyLoan/TestUngDung/Areas/Admin/Controllers/LoginController.cs
using ModelEF;
using ModelEF.Dao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestUngDung.Areas.Admin.Model;

namespace TestUngDung.Areas.Admin.Controllers
{
    public class LoginController : Controller
    {
        // GET: Admin/Login
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(LoginModel user)
        {
            if (ModelState.IsValid)
            {
                var dao = new UserDao();
                var result = dao.login(user.UserName, user.Password);
                if (result == 1)
                {
                    //ModelState.AddModelError("","Đăng nhập thành công");
                    Session.Add(Constants.USER_SESSION, user);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Đăng nhập không thành công");
                }
            }
            return View("Index");
        }
    } 
}

TranThiThuyLoan/TestUngDung/Areas/Admin/Controllers/ProductController.cs
using ModelEF.Dao;
using ModelEF.Model;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestUngDung.Areas.Admin.Controllers
{
    public class ProductController : Controller
    {
        // GET: Admin/Product

        public ActionResult Index(int page = 1, int pagesize = 5)
        {
            var pro = new ProductDao();
            var model = pro.ListAllPro();
            return View(model.ToPagedList(page, pagesize));
        }
        [HttpPost]
        public ActionResult Index(string searchString, int page = 1, int pagesize = 5)
            {
                var pro = new ProductDao();
                var model = pro.ListWhereAllPro(searchString, page, pagesize);
                ViewBag.SearchString = searchString;
                return View(model);
            }
            public ActionResult Detail(int id)
            {
                var pro = new ProductDao().FindPro(id);
                return View(pro);
            }
        
        [HttpGet]
        public ActionResult Create()
        {
            SetViewBag();
            return View();
        }
        public void SetViewBag(int? selectedId=null)
        {
            var dao = new CategoryDao();
            ViewBag.IDCate = new SelectList(dao.ListAllCa(),"ID","Name",selectedId);
        }
        [HttpPost]
        public ActionResult Create(Product model)
        {
            if (ModelState.IsValid)
            {
                var dao = new ProductDao();
                //SetViewBag();
                long result = dao.Insert(model);

                if (result > 0)
                {
                    return RedirectToAction("Index", "Product");
                }
                else
                {
                    ModelState.AddModelError("", "Tạo sản phẩm không thành công");
                }
            }
            SetViewBag();
            return View("Index");
        }
       
    }
}

TranThiThuyLoan/TestUngDung/Areas/Admin/Controllers/UserController.cs
using ModelEF.Dao;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestUngDung.Areas.Admin.Controllers
{
    public class UserController : Controller
    {
        // GET: Admin/User

        public ActionResult Index(int page = 1, int pagesize = 5)
        {
            var user = new UserDao();
            var model = user.ListAll();
            return View(model.ToPagedList(page, pagesize));
        }

        [HttpPost]
        public ActionResult Index(string searchString, int page = 1, int pagesize = 2)
        {
            var user = new UserDao();
            var model = user.ListWhereAll(searchString, page, pagesize);
            @ViewBag.SearchString = searchString;
            return View(model.ToPagedList(page, pagesize));
        }

        

        //[HttpDelete]
        public ActionResult Delete(int id)
        {
            new UserDao().Delete(id);
            return RedirectToAction("Index");
        }

    }
}

TranThiThuyLoan/TestUngDung/Controllers/HomeCustomController.cs
using ModelEF.Dao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestUngDung.Controllers
{
    public class HomeCustomController : Controller
    {
        // GET: HomeCustom
        public ActionResult Index()
        {
            var procus = new ProcustomDao();
            ViewBag.ProKhai = procus.ListProKhai();
            ViewBag.ProBo = procus.ListProBo();
            ViewBag.ProChuc = procus.ListProChuc();
            ViewBag.ProLe = procus.ListProLe();
            return View();
        }
    }
}

TranThiThuyLoan/TestUngDung/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Trang quản trị";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section Header{
    <i class="fa fa-home">  Trang quản trị</i>
}
Nội dung của trang quản trị

TranThiThuyLoan/TestUngDung/Areas/Admin/Views/Login/Index.cshtml
@model TestUngDung.Areas.Admin.Model.LoginModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="ThemeBucket">
    <link rel="shortcut icon" href="~/Assets/admin/favicon.png">

    <title>Login</title>

    <!--Core CSS -->
    <link href="~/Assets/admin/bs3/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Assets/admin/css/bootstrap-reset.css" rel="stylesheet">
    <link href="~/Assets/admin/font-awesome/css/font-awesome.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="~/Assets/admin/css/style.css" rel="stylesheet">
    <link href="~/Assets/admin/css/style-responsive.css" rel="stylesheet" />


</head>

<body class="login-body">

    <div class="container">
        <div class="form-signin">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, null, new { @class = "alert alert-danger" })
                <h2 class="form-signin-heading">Trang đăng nhập</h2>
                <div class="login-wrap">
                    <div class="user-login-info">
                        @Html.TextBoxFor(model => model.UserName, new { @class = "form-control", @placehoder = "Mời nhập tên đăng nhập", @autofocus = "autofocus" })
                        @Html.TextBoxFor(model => model.Password, new { @class = "form-control", @placehoder = "Mời nhập mật khẩu", @type = "password" })

                    </div>
                    <label class="checkbox">
                        <input type="checkbox" value="remember-me"> Nhớ mật khẩu
                        <span class="pull-right">
                            <a data-toggle="modal" href="#myModal"> Quên mật khẩu ?</a>

                        </span>
                    </label>
                    <button class="btn btn-lg btn-login btn-block" type="submit">Đăng nhập</button>

                    <div class="registration">
                        Bạn chưa có tài khoản ?
                        <a class="" href="registration.html">
                            Tạo tài khoản
                        </a>
                    </div>

                </div>

                <!-- Modal -->
                <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h4 class="modal-title">Quên mật khẩu ?</h4>
                            </div>
                            <div class="modal-body">
                                <p>Nhập email để đặt lại mật khẩu.</p>
                                <input type="text" name="email" placeholder="Email" autocomplete="off" class="form-control placeholder-no-fix">

                            </div>
                            <div class="modal-footer">
                                <button data-dismiss="modal" class="btn btn-default" type="button">Thoát</button>
                                <button class="btn btn-success" type="button">Hoàn thành</button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- modal -->

            }
        </div>
    </div>



    <!-- Placed js at the end of the document so the pages load faster -->
    <!--Core js-->
    <script src="~/Assets/admin/js/jquery.js"></script>
    <script src="~/Assets/admin/bs3/js/bootstrap.min.js"></script>

</body>
</html>

TranThiThuyLoan/TestUngDung/Areas/Admin/Views/Product/Create.cshtml
@model ModelEF.Model.Product

@{
    ViewBag.Title = "Tạo mới sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{
    <i class="fa fa-save"></i> Tạo mới sản phẩm
}

@using (Html.BeginForm("Create", "Product", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="col-lg-12 form-group">
            <div class="col-md-6">
                @Html.ActionLink("Quay lại", "Index", "Product", new { @class = "btn btn-primary" })
            </div>
        </div>
        <hr />
        <div class="col-lg-12 form-group">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.UnitCost, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.UnitCost, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UnitCost, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Quantity, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.IDCate,"IDCate" ,htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.IDCate,null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IDCate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Tạo mới" class="btn btn-danger" />
                </div>
            </div>
        </div>
    </div>
}

TranThiThuyLoan/TestUngDung/Areas/Admin/Views/Product/Detail.cshtml
@model ModelEF.Model.Product

@{
    ViewBag.Title = "Quản lý sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{
    <i class="fa fa-file-text-o"></i> Chi tiết sản phẩm
}


<div class="col-lg-12 form-group">
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Tên Sản phẩm</th>
            <th>Đơn giá</th>
            <th>Số lượng</th>
            <th>Mô tả</th>
            <th>Trạng thái</th>
            <th>LoaiSP_ID</th>
            <th>Image</th>
        </tr>
        <tr>
            <td>
                @Model.ID
            </td>
            <td>
                @Model.Name
            </td>
            <td>
                @Model.UnitCost
            </td>
            <td>
                @Model.Quantity
            </td>
            <td>
                @Model.Description
            </td>
            <td>
                @Model.Status
            </td>
            <td>
                @Model.Category.Name
            </td>
            <td>
                <img src=" @Url.Content("~/Image/"+@Model.Image)" height="50" width="50" />
            </td>
        </tr>

    </table>

</div>

TranThiThuyLoan/TestUngDung/Areas/Admin/Views/Product/Index.cshtml
@model PagedList.IPagedList<ModelEF.Model.Product>
@using PagedList.Mvc
@using PagedList;


@{
    ViewBag.Title = "Quản lý sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{
    <i class="fa fa-file-text-o"></i> Quản lý sản phẩm
}

@using (Html.BeginForm("Index", "Product", FormMethod.Post))
{
<div class="col-lg-12 form-group">
    <div class="col-md-6">
        @Html.ActionLink("Tạo mới", "Create", "Product", new { @class = "btn btn-danger" })
    </div>
    <div class="col-md-4">
        <input type="text" value="@ViewBag.SearchString" name="searchString" placeholder="Nhập từ khóa cần tìm kiếm" class="form-control">
    </div><div class="col-md-2">
        <input type="submit" value="Tìm kiếm" class="btn btn-default" />
    </div>
</div>
}
<div class="col-lg-12 form-group">
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Tên Sản phẩm</th>
            <th>Đơn giá</th>
            <th>Số lượng</th>
            <th>LoaiSP_ID</th>
            <th>Thao tác</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr id=" row_@item.ID">
                <td>
                    @item.ID
                </td>
                <td>
                    @item.Name
                </td>
                <td>
                    @item.UnitCost
                </td>
                <td>
                    @item.Quantity
                </td>
                <td>
                    @item.IDCate
                </td>
                <td>
                    @Html.ActionLink("Xem chi tiết", "Detail", "Product", new { @id = @item.ID }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
    </table>
    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page, @searchString = @ViewBag.SearchString }))
</div>

TranThiThuyLoan/TestUngDung/Areas/Admin/Views/Shared/_Header.cshtml
@using TestUngDung.Areas.Admin.Model;
@using ModelEF;
<header class="header fixed-top clearfix">
    <!--logo start-->
    <div class="brand">
        <a href="index.html" class="logo">
            <img src="~/Assets/admin/images/logo.png" alt="">
        </a>
        <div class="sidebar-toggle-box">
            <div class="fa fa-bars"></div>
        </div>
    </div>
    <!--logo end-->

    <div class="nav notify-row" id="top_menu">
        <!--  notification start -->
        <ul class="nav top-menu">
            <!-- settings start -->
            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <i class="fa fa-tasks"></i>
                    <span class="badge bg-success">8</span>
                </a>
                <ul class="dropdown-menu extended tasks-bar">
                    <li>
                        <p class="">You have 8 pending tasks</p>
                    </li>
                    <li>
                        <a href="#">
                            <div class="task-info clearfix">
                                <div class="desc pull-left">
                                    <h5>Target Sell</h5>
                                    <p>25% , Deadline  12 June’13</p>
                                </div>
                                <span class="notification-pie-chart pull-right" data-percent="45">
                                    <span class="percent"></span>
                                </span>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <div class="task-info clearfix">
                                <div class="desc pull-left">
                                    <h5>Product Delivery</h5>
                                    <p>45% , Deadline  12 June’13</p>
                                </div>
                                <span class="notification-pie-chart pull-right" data-percent="78">
                                    <span class="percent"></span>
                                </span>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <div class="task-info clearfix">
                                <div class="desc pull-left">
                                    <h5>Payment collection</h5>
                                    <p>87% , Deadline  12 June’13</p>
                                </div>
                                <span class="notification-pie-chart pull-right" data-percent="60">
                                    <span class="percent"></span>
                                </span>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <div class="task-info clearfix">
                                <div class="desc pull-left">
                                    <h5>Target Sell</h5>
                                    <p>33% , Deadline  12 June’13</p>
                                </div>
                                <span class="notification-pie-chart pull-right" data-percent="90">
                                    <span class="percent"></span>
                                </span>
                            </div>
                        </a>
                    </li>

                    <li class="external">
                        <a href="#">See All Tasks</a>
                    </li>
                </ul>
            </li>
            <!-- settings end -->
            <!-- inbox dropdown start-->
            <li id="header_inbox_bar" class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <i class="fa fa-envelope-o"></i>
                    <span class="badge bg-important">4</span>
                </a>
                <ul class="dropdown-menu extended inbox">
                    <li>
                        <p class="red">You have 4 Mails</p>
                    </li>
                    <li>
                        <a href="#">
                            <span class="photo"><img alt="avatar" src="~/Assets/admin/images/avatar-mini.jpg"></span>
                            <span class="subject">
                                <span class="from">Jonathan Smith</span>
                                <span class="time">Just now</span>
                            </span>
                            <span class="message">
                                Hello, this is an example msg.
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="photo"><img alt="avatar" src="~/Assets/admin/images/avatar-mini-2.jpg"></span>
                            <span class="subject">
                                <span class="from">Jane Doe</span>
                                <span class="time">2 min ago</span>
                            </span>
                            <span class="message">
                                Nice admin template
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="photo"><img alt="avatar" src="~/Assets/admin/images/avatar-mini-3.jpg"></span>
                            <span class="subject">
                                <span class="from">Tasi sam</span>
                                <span class="time">2 days ago</span>
                            </span>
                            <span class="message">
                                This is an example msg.
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="photo"><img alt="avatar" src="images/avatar-mini.jpg"></span>
                            <span class="subject">
                                <span class="from">Mr. Perfect</span>
                                <span class="time">2 hour ago</span>
                            </span>
                            <span class="message">
                                Hi there, its a test
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">See all messages</a>
                    </li>
                </ul>
            </li>
            <!-- inbox dropdown end -->
            <!-- notification dropdown start-->
            <li id="header_notification_bar" class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">

                    <i class="fa fa-bell-o"></i>
                    <span class="badge bg-warning">3</span>
                </a>
                <ul class="dropdown-menu extended notification">
                    <li>
                        <p>Notifications</p>
                    </li>
                    <li>
                        <div class="alert alert-info clearfix">
                            <span class="alert-icon"><i class="fa fa-bolt"></i></span>
                            <div class="noti-info">
                                <a href="#"> Server #1 overloaded.</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="alert alert-danger clearfix">
                            <span class="alert-icon"><i class="fa fa-bolt"></i></span>
                            <div class="noti-info">
                                <a href="#"> Server #2 overloaded.</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="alert alert-success clearfix">
                            <span class="alert-icon"><i class="fa fa-bolt"></i></span>
                            <div class="noti-info">
                                <a href="#"> Server #3 overloaded.</a>
                            </div>
                        </div>
                    </li>

                </ul>
            </li>
            <!-- notification dropdown end -->
        </ul>
        <!--  notification end -->
    </div>
    <div class="top-nav clearfix">
        <!--search & user info start-->
        <ul class="nav pull-right top-menu">
            <li>
                <input type="text" class="form-control search" placeholder=" Search">
            </li>
            <!-- user login dropdown start-->
            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <img alt="" src="~/Assets/admin/images/avatar1_small.jpg">
                    <span class="username">
                        @{
                            var session = (LoginModel)Session[Constants.USER_SESSION];
                        }
                        @if (session != null)
                        {@session.UserName;
                    }

                    </span>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu extended logout">
                    <li><a href="#"><i class=" fa fa-suitcase"></i>Trang cá nhân</a></li>
                    <li><a href="#"><i class="fa fa-cog"></i> Thiết lập</a></li>
                    <li>
                        <a href="@Url.Action("Logout", "Home")">
                            <i class="fa fa-key"></i> Thoát
                        </a>
                    </li>


                </ul>
            </li>
            <!-- user login dropdown end -->
            <li>
                <div class="toggle-right-box">
                    <div class="fa fa-bars"></div>
                </div>
            </li>
        </ul>
        <!--search & user info end-->
    </div>
</header>

TranThiThuyLoan/TestUngDung/Areas/Admin/Views/Shared/_Navigation.cshtml
<aside>
    <div id="sidebar" class="nav-collapse">
        <div class="leftside-navigation">
            <ul class="sidebar-menu" id="nav-accordion">
                <li>
                    <a class="active" href="@Url.Content("~/")">
                        <i class="fa fa-dashboard"></i>
                        <span>Quản trị viên</span>
                    </a>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fa fa-book"></i>
                        <span>Danh mục</span>
                    </a>
                    <ul class="sub">
                        <li><a href="@Url.Action("Index","User")"><i class="fa fa-folder-open-o"></i>Danh mục sản phẩm</a></li>
                        <li><a href=""><i class="fa fa-folder-open-o"></i>Thống kê sản phẩm</a></li>

                    </ul>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fa fa-book"></i>
                        <span>Quản lý</span>
                    </a>
                    <ul class="sub">
                        <li><a href="@Url.Action("Index","Product")"><i class="fa fa-folder-open-o"></i>Quản lý sản phẩm</a></li>
                        <li><a href=""><i class="fa fa-folder-open-o"></i>Quản lý đơn hàng</a></li>
                        <li><a href="@Url.Action("Index","User")"><i class="fa fa-user"></i>Quản lý khách hàng</a></li>
                        <li><a href="@Url.Action("Index","User")"><i class="fa fa-user"></i>Quản lý người dùng</a></li>
                    </ul>
                </li>

            </ul>
        </div>
    </div>
</aside>

TranThiThuyLoan/TestUngDung/Areas/Admin/Views/User/Index.cshtml
@model PagedList.IPagedList<ModelEF.Model.UserAccount>
@using PagedList.Mvc
@using PagedList;


@{
    ViewBag.Title = "Quản lý người dùng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{
    <i class="fa fa-user"></i> Quản lý người dùng
}

@using (Html.BeginForm("Index", "User", FormMethod.Post))
{
    <div class="col-lg-12 form-group">
        <div class="col-md-4">
            <input type="text" value="@ViewBag.SearchString" name="searchString" placeholder="Nhập từ khóa cần tìm kiếm" class="form-control">
        </div><div class="col-md-2">
            <input type="submit" value="Tìm kiếm" class="btn btn-default" />
        </div>
    </div>
}
<div class="col-lg-12 form-group">
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Cấu hình</th>
            <th>Tên đăng nhập</th>
            <th>Mật khẩu</th>
            <th>Status</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr id=" row_@item.ID">
                <td>
                    @item.ID
                </td>
                <td>
                    &nbsp;
                    @Ajax.ActionLink(" ", "Delete",new { id = item.ID }, new AjaxOptions
               {
                   Confirm = "Bạn có muốn xoá bản ghi này?",
                   OnComplete = "$('#row_" + item.ID + "').remove()",
                   HttpMethod = "Delete"
               }, new { @class = " glyphicon glyphicon-trash" })
                </td>
                <td>
                    @item.UserName
                </td>
                <td>
                    @item.Password
                </td>
                <td>
                    @item.Status
                </td>
            </tr>

        }
    </table>
    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page, @searchString = @ViewBag.SearchString }))
</div>